### ISSUE TITLE
Filter not working for countries with X-offset "-0px"

### ISSUE THREAD

**Issue by herchu** [DavidEGx/bga-arena-scoreboard#3]
I noticed the filter does not work for Argentina. Upon debugging from a fork, I figured the offsets starting with "-0px..." are obtained as "0px..." so any such country (Argentina, Albania and United Arab Emirates) fail to match and finding players from these countries fail.

**Comment by herchu** [comment]
I fixed it in this fork https://github.com/herchu/bga-arena-scoreboard

**Comment by DavidEGx** [comment]
Fixed in f5d893e5303451b0678aa3c12853b624385ffcf5

Thanks for the fix!
